# Generated by Django 5.0.6 on 2024-06-23 16:02

import django.db.models.deletion
import transactions.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_currency_options_alter_tag_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(validators=[transactions.validators.validate_not_future_date], verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, unique=True, verbose_name='Номер карты')),
                ('expiry_date', models.DateField(verbose_name='Срок действия')),
                ('name_on_card', models.CharField(max_length=100, verbose_name='Назание карты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'карта',
                'verbose_name_plural': 'карты',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.card', verbose_name='Карта'),
        ),
    ]
